package com.example.raghavapamula.marketsavant;

/**
 * Created by raghavapamula on 1/7/17.
 */

public class Wallet {/*

    public static int Bitcoin = 100;
    public static int Ethereum = 0;
    public static int Ripple = 0;
    public static int Litecoin = 0;
    public static int Monero = 0;
    public static int EthereumClassic = 0;
    public static int Dash = 0;
    public static int Augur = 0;
    public static int MaidSafeCoin = 0;
    public static int Steem = 0;
    public static int NEM = 0;
    public static int Iconomi = 0;
    public static int Factom = 0;
    public static int Dogecoin = 0;
    public static int Waves = 0;
    public static int Zcash = 0;
    public static int DigixDAO = 0;
    public static int StellarLumens = 0;
    public static int Tether = 0
    public static int Lisk
    public static int E-DinarCoin
    public static int Ardor
    public static int GameCredits
    public static int Swiscoin
    public static int Bytecoin
    public static int BitShares
    public static int ShadowCash
    public static int Golem
    public static int Gulden
    public static int Emercoin
    public static int Xaurum
    public static int AntShares
    public static int StorjcoinX
    public static int Siacoin
    public static int Stratis
    public static int Nxt
    public static int I/OCoin
    public static int Peercoin
    public static int SingularDTV
    public static int Counterparty
    public static int Rubycoin
    public static int LoMoCoin
    public static int YbCoin
    public static int SysCoin
    public static int BitcoinDark
    public static int AgorasTokens
    public static int Bitcrystals
    public static int PotCoin
    public static int Namecoin
    public static int Synereo
    public static int Yocoin
    public static int GlobalCurren...
    public static int DigiByte
    public static int Decred
    public static int NAVCoin
    public static int Byteball
    public static int SolarCoin
    public static int BlackCoin
    public static int SIBCoin
    public static int Nexus
    public static int GridCoin
    public static int Clams
    public static int SuperNET
    public static int vSlice
    public static int Aeon
    public static int Round
    public static int Scotcoin
    public static int SARCoin
    public static int Lykke
    public static int FedoraCoin
    public static int Omni
    public static int VPNCoin
    public static int SteemDollars
    public static int FairCoin
    public static int Veros
    public static int MonaCoin
    public static int EarthCoin
    public static int Auroracoin
    public static int CureCoin
    public static int Vertcoin
    public static int Expanse
    public static int Primecoin
    public static int Novacoin
    public static int Radium
    public static int FuelCoin
    public static int Burst
    public static int CloakCoin
    public static int BitBay
    public static int Mooncoin
    public static int Feathercoin
    public static int Adzcoin
    public static int Boolberry
    public static int NuBits
    public static int BitparkCoin
    public static int Creditbit
    public static int TrumpCoin
    public static int Viacoin
    public static int DigitalNote
    public static int Nexium
    public static int Mintcoin
    public static int Qora
    public static int GoldCoin
    public static int VeriCoin
    public static int HiCoin
    public static int Vcash
    public static int Energycoin
    public static int Asiadigicoin
    public static int NautilusCoin
    public static int ReddCoin
    public static int Quark
    public static int BlockPay
    public static int Megacoin
    public static int LBRYCredits
    public static int WorldCoin
    public static int FoldingCoin
    public static int DubaiCoin
    public static int PLAY
    public static int DNotes
    public static int OKCash
    public static int Gambit
    public static int ProjectDecorum
    public static int Breakout
    public static int BoostCoin
    public static int Darknet
    public static int Infinitecoin
    public static int BreakoutStake
    public static int FlorinCoin
    public static int ZcCoin
    public static int Obits
    public static int Startcoin
    public static int ICOOpenLedger
    public static int CircuitsofV...
    public static int SaluS
    public static int BelaCoin
    public static int Joincoin
    public static int LuckChain
    public static int Zetacoin
    public static int ZCoin
    public static int SafeExchange...
    public static int Blocknet
    public static int Riecoin
    public static int Rise
    public static int Diamond
    public static int GoldBlocks
    public static int CasinoCoin
    public static int EuropeCoin
    public static int Jumbucks
    public static int Voxels
    public static int Orbitcoin
    public static int Applecoin
    public static int ElectronicGu...
    public static int Digitalcoin
    public static int Myriad
    public static int GetGems
    public static int Cryptonite
    public static int NuShares
    public static int Verge
    public static int Bitmark
    public static int AmberCoin
    public static int Unobtanium
    public static int Silk
    public static int Virtacoin
    public static int vTorrent
    public static int BilShares
    public static int MazaCoin
    public static int Triggers
    public static int UnionCoin
    public static int HitCoin
    public static int WildBeastBlock
    public static int 2GIVE
    public static int Zeitcoin
    public static int HunterCoin
    public static int Swing
    public static int Fantomcoin
    public static int EvergreenCoin
    public static int Einsteinium
    public static int Horizon
    public static int Mineum
    public static int TagCoin
    public static int PinkCoin
    public static int StabilityShares
    public static int PepeCash
    public static int NeosCoin
    public static int CannabisCoin
    public static int SecureCoin
    public static int Woodcoin
    public static int bitCNY
    public static int PostCoin
    public static int MaxCoin
    public static int BitSwift
    public static int Synergy
    public static int ZClassic
    public static int BitcoinPlus
    public static int NobleCoin
    public static int PipCoin
    public static int Capricoin
    public static int ArtexCoin
    public static int Ixcoin
    public static int Jewels
    public static int Elcoin
    public static int Dimecoin
    public static int Flycoin
    public static int SmileyCoin
    public static int Crown
    public static int SpreadCoin
    public static int TheCypherfunks
    public static int bitUSD
    public static int WhiteCoin
    public static int Bitstar
    public static int ColossuscoinV2
    public static int Librexcoin
    public static int Tickets
    public static int MonetaryUnit
    public static int Coin2.1
    public static int Rubies
    public static int Shift
    public static int Blitzcash
    public static int Magi
    public static int Coin(O)
    public static int Stress
    public static int Rimbit
    public static int Stealthcoin
    public static int Bytecent
    public static int ArtByte
    public static int HempCoin
    public static int NetCoin
    public static int BitSend
    public static int Nyancoin
    public static int BillaryCoin
    public static int Dashcoin
    public static int Wexcoin
    public static int Qibuck
    public static int UltraCoin
    public static int GeoCoin
    public static int DopeCoin
    public static int Terracoin
    public static int Quatloo
    public static int NoLimitCoin
    public static int Sexcoin
    public static int Sterlingcoin
    public static int AtomicCoin
    public static int PutinCoin
    public static int Tao
    public static int Krypton
    public static int Pesobit
    public static int GoldPieces
    public static int Xiaomicoin
    public static int RussiaCoin
    public static int LTBcoin
    public static int Syndicate
    public static int CryptoBullion
    public static int Dotcoin
    public static int Cannacoin
    public static int Cryptojacks
    public static int TrustPlus
    public static int Moin
    public static int NeuCoin
    public static int bitBTC
    public static int Blakecoin
    public static int Truckcoin
    public static int DeutscheeMark
    public static int Espers
    public static int UniversalCur...
    public static int Sphere
    public static int Bata
    public static int Anoncoin
    public static int GPUCoin
    public static int Pesetacoin
    public static int ArcticCoin
    public static int BitBean
    public static int VeriumReserve
    public static int Influxcoin
    public static int Pakcoin
    public static int PascalCoin
    public static int TransferCoin
    public static int Bitland
    public static int Newbium
    public static int Bottlecaps
    public static int HyperStake
    public static int Memetic
    public static int Sling
    public static int Hyper
    public static int Karbowanec
    public static int Zayedcoin
    public static int BitBar
    public static int MojoCoin
    public static int CrevaCoin
    public static int Grantcoin
    public static int Elementrem
    public static int QuazarCoin
    public static int Titcoin
    public static int Triangles
    public static int Sativacoin
    public static int GlobalBoost-Y
    public static int Evotion
    public static int 1337
    public static int InsaneCoin
    public static int Veltor
    public static int Rawcoin
    public static int JIOToken
    public static int BERNcash
    public static int Joulecoin
    public static int X-Coin
    public static int Fastcoin
    public static int Bikercoin
    public static int DTToken
    public static int GCoin
    public static int Franko
    public static int ARbit
    public static int ZiftrCOIN
    public static int Beatcoin
    public static int BipCoin
    public static int BiosCrypto
    public static int JinCoin
    public static int CageCoin
    public static int Zurcoin
    public static int Prime-XI
    public static int FlavorCoin
    public static int Hommalicoin
    public static int Ratecoin
    public static int SOILcoin
    public static int VIPTokens
    public static int UniQredit
    public static int bitEUR
    public static int AllSafe
    public static int LeaCoin
    public static int NevaCoin
    public static int Halcyon
    public static int Guncoin
    public static int Chronos
    public static int CannabisIndu...
    public static int Bitzeny
    public static int Bolivarcoin
    public static int ParallelCoin
    public static int EvilCoin
    public static int GuccioneCoin
    public static int YashCoin
    public static int MetalMusicCoin
    public static int Cashout
    public static int EGO
    public static int Eternity
    public static int C-Bit
    public static int JobsCoin
    public static int HighVoltage
    public static int PrimeChain
    public static int TAGRcoin
    public static int LiteBar
    public static int NodeCoin
    public static int WorldGoldCoin
    public static int MudraCoin
    public static int TRMB
    public static int Peerplays
    public static int MUSE
    public static int Jinn
    public static int HackerGold
    public static int AsiaCoin
    public static int HTMLCOIN
    public static int ION
    public static int HempCoin
    public static int InstantDEX
    public static int Pandacoin
    public static int VootCoin
    public static int I0Coin
    public static int XCurrency
    public static int BTCtalkcoin
    public static int PangeaPoker
    public static int SwagBucks
    public static int Gycoin
    public static int SuperCoin
    public static int AudioCoin
    public static int Mediterranean...
    public static int Shorty
    public static int BTSR
    public static int Groestlcoin
    public static int Cryptofund
    public static int VaultCoin
    public static int BritCoin
    public static int TileCoin
    public static int TeslaCoin
    public static int CanadaeCoin
    public static int BlueCoin
    public static int Piggycoin
    public static int E-CurrencyCoin
    public static int IncaKoin
    public static int FlutterCoin
    public static int KoreCoin
    public static int Devcoin
    public static int Bitz
    public static int GlobalCoin
    public static int AurumCoin
    public static int TheViralExc...
    public static int BigUp
    public static int Kobocoin
    public static int KiloCoin
    public static int TittieCoin
    public static int RedCoin
    public static int Checkcoin
    public static int HOdlcoin
    public static int LIQUID
    public static int PetroDollar
    public static int LottoCoin
    public static int WayGuide
    public static int MarteXcoin
    public static int BBQCoin
    public static int ARCHcoin
    public static int MetalCoin
    public static int Quotient
    public static int SproutsExtreme
    public static int GAIA
    public static int bitSilver
    public static int PayCoin
    public static int Yacoin
    public static int Trollcoin
    public static int AmsterdamCoin
    public static int SatoshiMadness
    public static int ParkByte
    public static int Datacoin
    public static int LiteDoge
    public static int DigiCube
    public static int Dollarcoin
    public static int HoboNickels
    public static int SmartCoin
    public static int SecretCoin
    public static int Granite
    public static int UnbreakableCoin
    public static int ReeCoin
    public static int ExclusiveCoin
    public static int bitGold
    public static int Tigercoin
    public static int Cypher
    public static int Neutron
    public static int TEKcoin
    public static int CryptoEscudo
    public static int UCoin
    public static int 42Coin
    public static int Gapcoin
    public static int OctoCoin
    public static int Unitus
    public static int EmiratesGold...
    public static int Firecoin
    public static int CoExistCoin
    public static int CorgiCoin
    public static int MasterTraderCoin
    public static int ArcadeToken
    public static int AquariusCoin
    public static int BumbaCoin
    public static int Uro
    public static int Machinecoin
    public static int SongCoin
    public static int Creatio
    public static int Destiny
    public static int FujiCoin
    public static int Viral
    public static int BeaverCoin
    public static int QubitCoin
    public static int 8Bit
    public static int SpaceCoin
    public static int Nxttycoin
    public static int WARP
    public static int VapersCoin
    public static int PLNcoin
    public static int ZetaMicron
    public static int EmeraldCrypto
    public static int Cubits
    public static int SixEleven
    public static int SoonCoin
    public static int ChessCoin
    public static int Phoenixcoin
    public static int Freicoin
    public static int CyberCoin
    public static int RevolverCoin
    public static int HamRadioCoin
    public static int LanaCoin
    public static int BunnyCoin
    public static int Blackstar
    public static int GameBetCoin
    public static int PayCon
    public static int AntiBitcoin
    public static int IndependentM...
    public static int BitTokens
    public static int Cashcoin
    public static int MindCoin
    public static int Francs
    public static int AnarchistsPrime
    public static int Debitcoin
    public static int G3N
    public static int iCash
    public static int Spots
    public static int AgrolifeCoin
    public static int Orlycoin
    public static int WMCoin
    public static int Argentum
    public static int Unrealcoin
    public static int Zonecoin
    public static int PopularCoin
    public static int Acoin
    public static int Prototanium
    public static int IslaCoin
    public static int Pulse
    public static int DAPPSTER
    public static int Kittehcoin
    public static int Alexium
    public static int XP
    public static int GamerholicCoin
    public static int Crypto
    public static int FutureDigita...
    public static int Cabbage
    public static int MustangCoin
    public static int RonPaulCoin
    public static int Bitcloud
    public static int PX
    public static int Photon
    public static int Vcoin
    public static int B3Coin
    public static int Floz
    public static int NewYorkCoin
    public static int OsmiumCoin
    public static int Bitcoin21
    public static int LetItRide
    public static int 1CRedit
    public static int Litecred
    public static int MangoCoinz
    public static int Dobbscoin
    public static int 808Coin
    public static int Pospro
    public static int PhilosopherS...
    public static int PosEx
    public static int DigitalPrice
    public static int Guarany
    public static int ImpulseCoin
    public static int VirtualCoin
    public static int BitQuark
    public static int DPAY
    public static int Steps
    public static int Aricoin
    public static int Money
    public static int FuzzBalls
    public static int Comet
    public static int Eurocoin
    public static int Shilling
    public static int UniCoin
    public static int SydPak
    public static int Selfiecoin
    public static int ChainCoin
    public static int Antilitecoin
    public static int Regacoin
    public static int Hundredcoin
    public static int BlazeCoin
    public static int SaveandGain
    public static int BowsCoin
    public static int TajCoin
    public static int Revenu
    public static int Xonecoin
    public static int PonziCoin
    public static int DollarOnline
    public static int Powercoin
    public static int SwapToken
    public static int ImperialCoin
    public static int P7Coin
    public static int Levocoin
    public static int Zoin
    public static int Californium
    public static int CRTCoin
    public static int Enigma
    public static int PizzaCoin
    public static int DigitalCredits
    public static int Zcashshare
    public static int KhanCoin
    public static int 23Skidoo
    public static int SATOSHICARD
    public static int Forevercoin
    public static int Fargocoin
    public static int InternetofP...
    public static int Xenixcoin
    public static int NxttyACCI
    public static int RoyalCoin2
    public static int Pluton
    public static int BFX
    public static int TechShares
    public static int ClubCoin
    public static int LEOcoin
    public static int MaskCoin
    public static int Wowecoin
    public static int PabyosiCoin...
    public static int Decent
    public static int IndexCoin
    public static int TheDAO
    public static int AxFunds
    public static int HEATLedger
    public static int WASpace
    public static int PandaGold
    public static int International...
    public static int AlpaCoin
    public static int TBCoin
    public static int FirstBlood
    public static int Incent
    public static int TeslaCoilCoin
    public static int DeepWebCash
    public static int Omicron
    public static int Golos
    public static int BigLifeCoin
    public static int EDRCoin
    public static int MindGene
    public static int GBCGoldCoin
    public static int PresidentJoh...
    public static int DynamicCoin
    public static int TROPTIONS
    public static int InvisibleCoin
    public static int LeCoin
    public static int Timekoin
    public static int Vibranium
    public static int DeltaCredits
    public static int Zdash
    public static int Lepaoquan
    public static int CaliphCoin
    public static int KolschCoin
    public static int Sharkcoin
    public static int HappyCreator...
    public static int AdvancedInte...
    public static int RubleBit
    public static int GSSCoin
    public static int BagCoin
    public static int Digitalfund
    public static int FuturePoints
    public static int Rhodiumcoin
    public static int PresidentTrump
    public static int Xaucoin
    public static int GlobalBusine...
    public static int AlphabetCoin...
    public static int ShellPay
    public static int RoyalCoin
    public static int EggCoin
    public static int TaoPay
    public static int TrickyCoin
    public static int BitcoinScrypt
    public static int FirstBitcoin
    public static int PoSWCoin
    public static int Neptunecoin
    public static int FutCoin
    public static int CHNCoin
    public static int Clinton
    public static int netBit
    public static int Psilocybin
    public static int RichCoin
    public static int Peacecoin
    public static int UNCoin
    public static int GoldMaxCoin
    public static int T-coin
    public static int OCOW
    public static int GameLeagueCoin
    public static int Motocoin
    public static int LocalFamily...
    public static int DigitalBulli...
    public static int BitAlphaCoin
    public static int FrankyWillCoin
    public static int Kurrent
    public static int BitcoinFast
    public static int Bitcurrency
    public static int Opescoin
    public static int Dubstep
    public static int AsicCoin
    public static int FedoraShare
    public static int MobileCash
    public static int AvatarCoin
    public static int TodayCoin
    public static int Lazaruscoin
    public static int Sakuracoin
    public static int CBDCrystals
    public static int Wowcoin
    public static int Quebecoin
    public static int Flaxscript
    public static int LinkedCoin
    public static int Braincoin
    public static int PabyosiCoin
    public static int Operand
    public static int SportsCoin
    public static int FitCoin
    public static int Skeincoin
    public static int VegasCoin
    public static int CyclingCoin
    public static int Moneta
    public static int PrismChain
    public static int UGAIN
    public static int Rcoin
    public static int LAthaan
    public static int TeamUp
    public static int DigiEuro
    public static int PayPeer
    public static int TheCreed
    public static int SafeCoin
    public static int MoneyCoin
    public static int SuperTurboStake
    public static int Valorbit
    public static int SuperStakeToken
    public static int GanjaCoinV2
    public static int FireFlyCoin
    public static int Zcrypt
    public static int Victoriouscoin
    public static int X2
    public static int SoulCoin
    public static int PokeCoin
    public static int PresidentCli...
    public static int Aces
    public static int Golfcoin
    public static int Tellurion
    public static int ChoofCoin
    public static int Cashme
    public static int Paccoin
    public static int LunaCoin
*/


}
